<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="22834" started-at="2019-02-17T09:30:19Z" finished-at="2019-02-17T09:30:41Z">
    <groups>
      <group name="cucumber">
        <method signature="AbstractTestNGCucumberTests.runScenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.frank.cucumberframework.testrunners.WebTestRunner@157632c9]" name="runScenario" class="cucumber.api.testng.AbstractTestNGCucumberTests"/>
      </group> <!-- cucumber -->
    </groups>
    <test name="Surefire test" duration-ms="22834" started-at="2019-02-17T09:30:19Z" finished-at="2019-02-17T09:30:41Z">
      <class name="com.frank.cucumberframework.testrunners.WebTestRunner">
        <test-method status="PASS" signature="setUpClass()[pri:0, instance:com.frank.cucumberframework.testrunners.WebTestRunner@157632c9]" name="setUpClass" is-config="true" duration-ms="484" started-at="2019-02-17T09:30:19Z" finished-at="2019-02-17T09:30:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpClass -->
        <test-method status="FAIL" signature="runScenario(cucumber.api.testng.PickleEventWrapper, cucumber.api.testng.CucumberFeatureWrapper)[pri:0, instance:com.frank.cucumberframework.testrunners.WebTestRunner@157632c9]" name="runScenario" duration-ms="21782" started-at="2019-02-17T09:30:19Z" description="Runs Cucumber Scenarios" data-provider="scenarios" finished-at="2019-02-17T09:30:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA["Success"]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Web Login"]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[URL judgement has been failed!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: URL judgement has been failed!
at org.testng.Assert.fail(Assert.java:96)
at com.frank.cucumberframework.stepdefinition.web.LoginTestSteps.enterIntoDashboard(LoginTestSteps.java:68)
at âœ½.redirect to dashboard page(src/test/resources/features/web_login.feature:7)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runScenario -->
        <test-method status="PASS" signature="tearDownClass()[pri:0, instance:com.frank.cucumberframework.testrunners.WebTestRunner@157632c9]" name="tearDownClass" is-config="true" duration-ms="100" started-at="2019-02-17T09:30:41Z" finished-at="2019-02-17T09:30:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownClass -->
      </class> <!-- com.frank.cucumberframework.testrunners.WebTestRunner -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
