<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LiuYongjian" name="com.frank.cucumberframework.testrunners.WebTestRunner" tests="1" failures="1" timestamp="17 二月 2019 09:30:42 GMT" time="21.782" errors="0">
  <testcase name="runScenario" time="21.782" classname="com.frank.cucumberframework.testrunners.WebTestRunner">
    <failure type="java.lang.AssertionError" message="URL judgement has been failed!">
      <![CDATA[java.lang.AssertionError: URL judgement has been failed!
at org.testng.Assert.fail(Assert.java:96)
at com.frank.cucumberframework.stepdefinition.web.LoginTestSteps.enterIntoDashboard(LoginTestSteps.java:68)
at ✽.redirect to dashboard page(src/test/resources/features/web_login.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.frank.cucumberframework.testrunners.WebTestRunner -->
